[package]
name = "mongo"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = { version = "3.2.1", features = ["sync"] }
serde_json = "1.0"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
dotenv = "0.15"

